name: Roadmap Item
description: Create an issue report to help us improve
title: "<title>"
labels: [future]
body:
- type: textarea
  attributes:
    label: Summary
    description: Please describe the issue you are experience as detailed and consised as possible.
  validations:
    required: true
- type: textarea
  attributes:
    label: Intended Outcome
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: How will it work?
    description: |
      Links? References? Log files? Code snippets?
      Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
